version: "3"

services:
  app:
    build:
      context: ./docker
    volumes:
      - ./laravel-app:/var/www/app
    ports:
      - "9000:80"
    working_dir: /var/www/app
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/app/public
      TZ: "Asia/Tokyo"

  db:
    image: mysql:5.7
    ports:
      - "4000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_DATABASE: database
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      TZ: "Asia/Tokyo"

  testdb:
    image: mysql:5.7
    ports:
      - "4001:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: test_user
      MYSQL_DATABASE: test_database
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      TZ: "Asia/Tokyo"
